language: ruby
before_script:
  - rm -rf ./spec/vocabularies
  - rm -rf ./coverage
  - rm -rf ./doc
  - rm -rf ./.yardoc
script:
  - bundle install
  - bundle exec rails r -e test "DatabaseCleaner.clean"
  - COVERAGE=true bundle exec rake parallel:spec[2]
  - bundle exec cucumber -f rerun --out tmp/cucumber_failures.log
  - bundle exec rake yard
os:
  - linux
services:
  - mongodb
